export const GET_PRODUCT_FROM_BASE = 'GET_PRODUCT_FROM_BASE';

export const SET_PRODUCT_LIMITED = 'SET_PRODUCT_LIMITED';
export const SET_PRODUCT_UNLIMITED = 'SET_PRODUCT_UNLIMITED';

export const SAVE_PRODUCT_TO_BASE = 'SAVE_PRODUCT_TO_BASE';
